server:
  port: 8080
#spring:
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://localhost:3306/windsound?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver
#mybatis:
#  mapper-locations: classpath:mapping/*Mapper.xml
#  type-aliases-package: com.windsound.project.entity
#logging:
#  level:
#    com:
#      windsound:
#        project:
#          mapper: debug
spring:
  datasource:
    db2:
      username: root
      password: 123456
      jdbc-url: jdbc:mysql://localhost:3306/windsound?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
    db1:
      username: root
      password: 123456
      jdbc-url: jdbc:mysql://localhost:3306/windsound?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
